language: cpp
os: ubuntu
dist: xenial
compiler:
- clang
- gcc
sudo: required
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo apt-get update -y;
    sudo apt-get upgrade -y;
    sudo apt-get dist-upgrade -y;
    eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)";
  fi
install:
- sudo apt-get update -qq
- sudo apt-get install cmake dpkg-dev libyajl-dev libssl-dev libboost1.58-dev libboost-system1.58-dev libboost-atomic1.58-dev libboost-chrono1.58-dev libboost-date-time1.58-dev libboost-filesystem1.58-dev libboost-program-options1.58-dev libboost-regex1.58-dev libboost-thread1.58-dev libboost-timer1.58-dev
script:
- cd src
# - make test
- cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -D CMAKE_AGENT_COMPILER=gcc
- oclint-json-compilation-database
