# To use directly, run: docker build --build-arg package=<pkg>.trusty.deb -t <tag> -f Dockerfile-trusty
FROM ubuntu:trusty

ARG package
COPY ${package} /
RUN apt-get update \
    && (dpkg -i /${package} || true) \
    && apt-get install -f -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /${package}

CMD /opt/stackdriver/metadata/sbin/metadatad

EXPOSE 8000
