MetadataIngestionEndpointFormat: "https://staging-stackdriver.sandbox.googleapis.com/v1beta2/projects/{{project_id}}/monitoredResourceMetadata:batchUpdate"
#CredentialsFile: /tmp/token.json
#ProjectId: "1234567890"
#InstanceZone: "us-central1-a"
#DockerContainerFilter: "limit=1"
