steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/metadata-agent-xenial-build-container
  - build/x86_64_xenial
- name: 'gcr.io/cloud-builders/docker'
  args:
  - run
  - -v
  - /workspace:/workspace
  - -w
  - /workspace/src/
  - gcr.io/$PROJECT_ID/metadata-agent-xenial-build-container
  - /bin/bash
  - -c
  - make purge && make -j4 DEB_PKG=stackdriver-metadata.deb DISTRO=xenial deb
# TODO: Remove the need for this `cp` build step.
- name: 'ubuntu:xenial'
  args: 
  - cp
  - /workspace/src/stackdriver-metadata.deb
  - /workspace/pkg/docker/stackdriver-metadata.deb
- name: 'gcr.io/cloud-builders/docker'
  args:
  - build
  - --build-arg
  - package=stackdriver-metadata.deb
  - -t
  - gcr.io/$PROJECT_ID/metadata-agent-xenial:$BUILD_ID
  - -f
  - pkg/docker/Dockerfile-xenial
  - pkg/docker
images:
# The $BUILD_ID can be used to inspect the build logs to determine the version
# of the metadata agent that is included in the build.
- 'gcr.io/$PROJECT_ID/metadata-agent-xenial:$BUILD_ID'

